apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-go
  labels:
    app: actors-go
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: actors-go
  template:
    metadata:
      labels:
        app: actors-go
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "actors-go"
        dapr.io/config: "daprconfig"
        dapr.io/app-port: "6010"
        # dapr.io/log-level: "debug"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: actors-go
        image: localhost:5001/actors-go:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
