allow_k8s_contexts('kind-kind')

load('./tools/dapr/Tiltfile', 'dapr', 'dapr_config_component')
load('./tools/zipkin/Tiltfile', 'zipkin')
load('./tools/redis/Tiltfile', 'redis', 'redis_pubsub_component', 'redis_state_component', 'redis_workflowstate_component')
load('./tools/postgres/Tiltfile', 'postgres', 'postgres_state_component', 'postgres_workflowstate_component')
load('./tools/kafka/Tiltfile', 'kafka', 'kafka_oidc_jwt', 'kafka_pubsub_component', 'kafka_kafka_oidc_jwt_pubsub_component')
load('./tools/pulsar/Tiltfile', 'pulsar', 'pulsar_pubsub_component')

local('helm repo update')
zipkin()
# dapr("dev")
dapr("1.16.6")
dapr_config_component(zipkin_endpoint='http://zipkin.default.svc.cluster.local:9411/api/v2/spans')

redis()
# postgres()
# kafka()
# kafka_oidc_jwt()
# pulsar()

redis_pubsub_component()
# pulsar_pubsub_component()
# kafka_pubsub_component()
# kafka_kafka_oidc_jwt_pubsub_component()

redis_state_component()
# postgres_state_component()

redis_workflowstate_component()
# postgres_workflowstate_component()

# load_dynamic('apps/actors-go/Tiltfile')
# load_dynamic('apps/pub/Tiltfile')
# load_dynamic('apps/sub/Tiltfile')
load_dynamic('apps/workflows-py/Tiltfile')
# load_dynamic('apps/bug-py/Tiltfile')
# load_dynamic('apps/workflows-crossapp/Tiltfile')
# load_dynamic('apps/workflows-go/Tiltfile')
# load_dynamic('apps/workflows-stress/Tiltfile')
# load_dynamic('apps/dapr-agents/Tiltfile')
# load_dynamic('apps/tracing-dotnet/Tiltfile')
# load_dynamic('apps/workflows-full-py/Tiltfile')
# load_dynamic('apps/bindings-py/Tiltfile')
# load_dynamic('apps/agent-simple/Tiltfile')

