load('ext://uibutton', 'cmd_button')

# Workflows service (Go)
docker_build('localhost:5001/workflows-go', '.')
k8s_yaml('manifests/deployment.yaml')
k8s_resource(workload='workflows-go', resource_deps=['dapr'], labels=['apps'], port_forwards=['6006:6006'])

cmd_button('workflows-go:start',
            argv=['sh', '-c', 'curl --silent -X POST http://localhost:6006/start'],
            resource='workflows-go',
            icon_name='cloud_download',
            text='start workflow',
)
