apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflows-stress
  labels:
    app: workflows-stress
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: workflows-stress
  template:
    metadata:
      labels:
        app: workflows-stress
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "workflows-stress"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: workflows-stress
        image: localhost:5001/workflows-stress:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
