apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflowstatestore
spec:
  type: state.postgresql
  version: v2
  metadata:
  - name: connectionString
    value: postgres://dapr:dapr@dapr-postgres-postgresql.default.svc.cluster.local:5432/dapr_test
