apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-grpc-py
  labels:
    app: actors-grpc-py
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: actors-grpc-py
  template:
    metadata:
      labels:
        app: actors-grpc-py
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "actors-grpc-py"
        dapr.io/config: "daprconfig"
        dapr.io/app-port: "6011"
        dapr.io/app-protocol: "grpc"
        dapr.io/env: "OTEL_SERVICE_NAME=daprd"
        # dapr.io/log-level: "debug"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: actors-grpc-py
        image: localhost:5001/actors-grpc-py:latest
        ports:
        - containerPort: 6011
        env:
        - name: APP_PORT
          value: "6011"
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
