apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-py
  labels:
    app: secrets-py
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: secrets-py
  template:
    metadata:
      labels:
        app: secrets-py
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "secrets-py"
        dapr.io/app-port: "6005"
        dapr.io/config: "secrets-py-config"
        dapr.io/log-level: "debug"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: secrets-py
        image: localhost:5001/secrets-py:latest
        ports:
        - containerPort: 6005
        env:
        - name: APP_PORT
          value: "6005"
        - name: STATE_STORE_NAME
          value: "secret-statestore"
        - name: STATE_KEY
          value: "mykey"
        - name: LOOP_INTERVAL_SECONDS
          value: "5"
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
